// This file is automatically generated by Vite PWA plugin
const { registerSW } = window;

// Check that service workers are supported
if ('serviceWorker' in navigator) {
  // Wait for the 'load' event to not block other work
  window.addEventListener('load', async () => {
    try {
      const registration = await registerSW({
        onNeedRefresh() {
          if (confirm('New content available! Reload to update?')) {
            registration.update().then(() => window.location.reload());
          }
        },
        onOfflineReady() {
          console.log('App ready to work offline');
        },
        onRegisterError(error) {
          console.error('Error during service worker registration:', error);
        },
      });
    } catch (error) {
      console.error('Error registering service worker:', error);
    }
  });
}
