version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - CLIENT_URL=http://localhost:3000
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # For development with hot-reload
  dev:
    build:
      context: .
      target: builder
    command: sh -c "npm run dev"
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3001:3001"
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - CLIENT_URL=http://localhost:5173
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis

volumes:
  redis_data:
