services:
  # Combined Frontend + Backend Service
  - type: web
    name: ephemeral-chat
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: ROOM_EXPIRY_MINUTES
        value: 10
      - key: MAX_MESSAGES_PER_MINUTE
        value: 30
